# Exclude a variety of commonly ignored directories.
src = ["acoular"]
exclude = ["tests/unsupported", "docs/source", ".git/"]
    
line-length = 120
indent-width = 4

[lint]
select = [
        "F", # pyflakes
        "C","E","R", "W",  # pylint (including pycodestyle)
        "C90", "I", "N","D", "UP", 
        "YTT", "ASYNC", "TRIO", "BLE", "B", "A", "COM", # flake8 plugins
        "C4", "DTZ","T10","EM", "FA", "ISC", "ICN", # flake8 plugins
        "LOG", "G", "INP", "PIE", "T20", "PYI", "PT", "RSE", # flake8 plugins
        "RET", "SLF", "SLOT", "SIM", "TID", "TCH", "INT", "ARG", "TD", "FIX", # flake8 plugins
        "C901" # others
        ]

ignore = [
    "E501", # ignore line length until fixed through issue #214
    "C901", # do we want to measure code complexity -> TBD
    "COM812", # conflict with ruff formatter 
    "ISC001", # conflict with ruff formatter
    # D
    "D203", # don't enforce blank line before docstring
    "D401", # first line should be in imperative mood -> TBD
    "D205", # 1 blank line required between summary line and description -> should be fixed by issue #216
    "D100", # missing docstring in public module -> should be fixed by issue #216
    "D101", # missing docstring in public class -> should be fixed by issue #216
    "D102", # missing docstring in public method -> should be fixed by issue #216
    "D103", # missing docstring in public function -> should be fixed by issue #216
    "D104", # missing docstring in public package -> should be fixed by issue #216
    "D105", # missing docstring in magic method -> should be fixed by issue #216
    "D107", # missing docstring in __init__ -> should be fixed by issue #216
    "D417", # missing argument descriptions in the docstring -> should be fixed by issue #216
    # Others
    "INP", # will be fixed when test are moved
    "T20", # will be fixed when logging is implemented
    "PT", # will be solved when test infrastructure is refactored
    "SLF001", # should be fixed with issue: #225 
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[lint.pydocstyle]
convention = "numpy"  # Accepts: "google", "numpy", or "pep257".

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"


[lint.per-file-ignores]
"acoular/__init__.py" = ["F401"] 
"acoular/demo/__init__.py" = ["F401"] 
"acoular/tools/__init__.py" = ["F401"] 
"acoular/fastFuncs.py" = ["N802", "N803","N806","N999"] # allow different naming convention
"acoular/environments.py" = ["N806"] 
"acoular/sources.py" = ["N806"] 
"acoular/tbeamform.py" = ["F841","N806"] 
"acoular/tprocess.py" = ["N806"] #
"acoular/fbeamform.py" = ["N806","B023"] 
"tests/test_tprocess.py" = ["F403"] 
"tests/*" = ["D", "N", "SLF001", "TD002", "TD003", "FIX002"] # exclude docstring and naming conventions linting -> must be handled when tests are refactored
"examples/*" = ["A001", "B007", "D4", "E4", "E701", "F4", "UP036", "SIM108","SLF001"]
