blank_issues_enabled: true
contact_links:
  - name: Having a question or need support?
    url: https://github.com/acoular/acoular/discussions
    about: Ask the community for help via GitHub Discussions.