package:
  name: acoular
  version: "{{ environ.get('VERSION') }}"

source:
  path: ..

build:
  noarch: python
  script: python -m pip install --no-deps -vv .

requirements:
  host:
    - python
    - pip
    - hatchling
    - wheel
  run:
    - python >=3.10
    - scikit-learn 
    - numba
    - numpy
    - scipy
    - traits
    - pytables

test:
  source_files: # from acoular folder
    - acoular/xml/
    - examples/
  imports:
    - acoular

about:
  home: http://www.acoular.org
  license: BSD License
  summary: 'Library for acoustic beamforming'
