package:
  name: acoular
  version: "15.02.10"

source:
  path: ../../acoular

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - acoular = acoular:main
    #
    # Would create an entry point called acoular that calls acoular.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.8
    - scipy >=0.13
    - scikit-learn >=0.15
    - pytables >=3.1
    - traits >=4.4
    - chaco >=4.4

  run:
    - python
    - numpy >=1.8
    - scipy >=0.13
    - scikit-learn >=0.15
    - pytables >=3.1
    - traits >=4.4
    - chaco >=4.4

test:
  # Python imports
  imports:
    - acoular

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.acoular.org
  license: BSD License
  summary: 'Library for acoustic beamforming'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
