name: 'Set up hatch'
description: 'Set up Python, upgrade pip and install hatch'
inputs:
  python-version:
    description: 'The Python version'
    required: false
    default: '3.13'
runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      shell: bash
    - name: Install hatch
      run: python -m pip install hatch
      shell: bash
