name: "Manual: Conda 🐍 Build 🛠️ & Deploy"
run-name: Build Pkg 🛠️ & Publish to Anaconda 🐍
permissions:
  contents: read
on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    environment: anaconda
    uses: acoular/ci/.github/workflows/conda.yml@main
    with:
      deploy: true
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
