name: Docs Build & Deploy (dev)
run-name: Build & Deploy docs → acoular/dev
permissions:
  contents: read
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    uses: acoular/ci/.github/workflows/docs.yml@main
    with:
      artifact_name: build-docs-dev
      artifact_path: ./docs/_build/html
      html_baseurl: "https://acoular.org/acoular/dev/"
      docs_version_match: "dev"
      docs_switcher_json_url: "https://acoular.org/acoular/_static/switcher.json"

  deploy:
    needs: build
    uses: acoular/ci/.github/workflows/package-docs-deploy.yml@main
    with:
      artifact_name: build-docs-dev
      artifact_path: ./docs/_build/html
      destination_dir: acoular/dev
      package_path: /acoular
      min_version: v26.01
      deploy_switcher: true
      switcher_destination_dir: acoular/_static
    secrets:
      website_gh_pages_token: ${{ secrets.WEBSITE_GH_PAGES_TOKEN }}
