name: Acoular linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install acoular
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"
    - name: Lint
      run: |
        ruff check acoular
    
            
    

    