name: Acoular linting

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install acoular and lint
        run: |
            python -m pip install --upgrade pip
            pip install ".[dev]"
            ruff check acoular
    
            
    

    