name: Acoular 👁️ Organizational CI
permissions:
  contents: read
on:
  pull_request:
    branches: [ master ]

jobs:
  conda:
    uses: acoular/ci/.github/workflows/conda.yml@main

  coverage:
    uses: acoular/ci/.github/workflows/coverage.yml@main
    permissions:
      contents: read
      pull-requests: write

  docs:
    uses: acoular/ci/.github/workflows/docs.yml@main
    with:
      artifact_name: build-docs-dev
      artifact_path: ./docs/_build/html
      html_baseurl: "https://acoular.org/acoular/dev/"
      docs_version_match: dev

  linting:
    uses: acoular/ci/.github/workflows/linting.yml@main

  pypi:
    uses: acoular/ci/.github/workflows/pypi.yml@main

  tests:
    uses: acoular/ci/.github/workflows/tests.yml@main
