# This workflow will install acoular and run tests a variety of Python versions

name: Acoular install and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }} 

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9','3.10','3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install acoular
      run: |
        python -m pip install --upgrade pip
        pip install .
        python -c 'import acoular'
    - name: Test with unittest *nix
      run: |
        chmod +x ../acoular/acoular/tests/run_tests.sh
        cd ../acoular/acoular/tests/
        bash run_tests.sh
      if: ${{ matrix.os != 'windows-latest'}}
    - name: Test with unittest Windows
      run: |
        cd ..\acoular\acoular\tests
        python -m unittest discover -v -p "test_*.py"
      if: ${{ matrix.os == 'windows-latest'}}


