name: Release CI ✴️
permissions:
  contents: read
on:
  release:
    types: [ published ]

jobs:
  conda:
    environment: anaconda
    uses: acoular/ci/.github/workflows/conda.yml@main
    with:
      deploy: true
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

  docs_versioned:
    uses: acoular/ci/.github/workflows/docs.yml@main
    with:
      deploy: true
      package: acoular
      version: ${{ github.ref_name }}
      artifact_name: build-docs-versioned
      artifact_path: ./docs/_build/html
      html_baseurl: "https://acoular.org/acoular/${{ github.ref_name }}/"
      min_version: v26.01
      deploy_switcher: true
    secrets:
      website_gh_pages_token: ${{ secrets.WEBSITE_GH_PAGES_TOKEN }}

  docs_stable:
    needs: docs_versioned
    uses: acoular/ci/.github/workflows/docs.yml@main
    with:
      deploy: true
      package: acoular
      artifact_name: build-docs-stable
      artifact_path: ./docs/_build/html
      html_baseurl: "https://acoular.org/acoular/"
    secrets:
      website_gh_pages_token: ${{ secrets.WEBSITE_GH_PAGES_TOKEN }}

  pypi_build:
    uses: acoular/ci/.github/workflows/pypi.yml@main

  pypi_publish:
    needs: pypi_build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: package-build
          path: dist/
      - name: Publish distribution
        run: uv publish --index pypi
